### ISSUE TITLE
Isn't java.util.Iterator considered a functional interface?

### ISSUE THREAD

**Issue by dayserivera** [eh3rrera/ocpj8-book#25]
Part THREE - Lambda Expressions
Chapter EIGHT - Functional Interfaces
Isn't java.util.Iterator considered a functional interface?
The answer of the question 4 says only A. java.util.concurrent.Callable and D. java.lang.Comparable are considered functional interfaces. I checked the java.util.Iterator, it has only 3 methods, 2 of them are default.

**Comment by eh3rrera** [comment]
Hi @dayserivera,

Maybe you're checking the documentation of an earlier version.

https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html

Now, java.util.Iterator has two abstract methods and two default methods.

**Comment by dayserivera** [comment]
Sorry, I was checking Iterable.
Thanks for the answer!!

**Comment by eh3rrera** [comment]
No problem, it happens :)
