### ISSUE TITLE
Code error in Chapter 4

### ISSUE THREAD

**Issue by mrizwansarwar** [eh3rrera/ocpj8-book#27]
The following code does not compile due to return type mismatch

`interface CompactCar {
	int accelerate();
}
class Car implements CompactCar {
	@Override
	public void accelerate() {
		// implementation
	}
}`

**Comment by eh3rrera** [comment]
Fixed, the implementation must return `int` instead of `void`.

Thanks again!

**Comment by mrizwansarwar** [comment]
The above problem is repeated in the code snippet the appears after this one. I am assuming that the typo that is intended is the difference in method name only but again the return types are different.

**Comment by eh3rrera** [comment]
Yes, I didn't see it.

It's fixed now, thanks.
