### ISSUE TITLE
Exam objective not covered

### ISSUE THREAD

**Issue by PetrusKruger** [eh3rrera/ocpj8-book#29]
The following exam objective is not covered in chapter 1:
Override hashCode, equals, and toString methods from Object class.

**Comment by eh3rrera** [comment]
You're right, it's covered in chapter 2. I moved that objective from chapter 1 to chapter 2.

Thanks!

**Comment by PetrusKruger** [comment]
Hi Esteban

I did notice that afterwards. Thank you for your speedy response.

Much Appreciated

Regards

Petrus

**Comment by eh3rrera** [comment]
Thanks to you Petrus 😃
