### ISSUE TITLE
Small mistake in key point section of Chapter 15 : Data Search

### ISSUE THREAD

**Issue by HermiGinger** [eh3rrera/ocpj8-book#3]
Mistake : Both allMatch() and noneMatch() return **_false_** if the stream is empty.

Correct : Both allMatch() and noneMatch() return **_true_** if the stream is empty.

**Comment by eh3rrera** [comment]
Thank you so much @HermiGinger 

It's fixed here and on the website now. Can we close the issue or do you have another comment?
