### ISSUE TITLE
Chapter 4 - Interfaces

### ISSUE THREAD

**Issue by dpanjabi** [eh3rrera/ocpj8-book#34]
"You can't create an interface directly, it has to be implemented by a class to use it."

should be replaced with

"You can't instantiate an interface directly, it has to be implemented by a class to use it."

**Comment by eh3rrera** [comment]
You're right, the correct word is _instantiate_.

It's fixed now: http://ocpj8.javastudyguide.com/ch04.html

Thanks a lot
