### ISSUE TITLE
Chapter 2 - definition of a method signature

### ISSUE THREAD

**Issue by IvanMwiruki** [eh3rrera/ocpj8-book#35]
This chapter states twice "In a few words, the method signature is the name of the method and the list (types and names included) of its parameters." 

The names of the parameters are not included in a Java method signature, but the number of parameters is. The signature is name, types of parameters, numbers of parameters.

**Comment by eh3rrera** [comment]
You're right, it's fixed now

Thanks a lot @IvanMwiruki 👍

**Comment by IvanMwiruki** [comment]
Thanks. Also, where did you learn so much about Java? Aka what are some good resources? I've looked at books, oracles documentation, source code, stackoverflow, etc.

**Comment by eh3rrera** [comment]
Thanks for your kind words. I learned Java a long time ago, I think studying for the certification gives you a good knowledge of the language, that it helps a lot, but nothing beats practice, just pick a combination of tools/frameworks and create something. This will require you to search for ways to do something using all types of resources (books, youtube, documentation, SO), as a result, you'll understand it better and gain more experience.

Having said that, I also recommend to read a lot of books. For example, this [page](http://javarevisited.blogspot.mx/2013/01/top-5-java-programming-books-best-good.html) has a list of good books related to Java. Here's [another one](https://blog.codinghorror.com/recommended-reading-for-developers/) for programming in general.

I suggest a [Safari](https://www.safaribooksonline.com) subscription. It's a bit expensive, but something not many people know is that if you have an [ACM](http://www.acm.org) subscription (99 USD a year or [less if you're from a developing country](https://campus2.acm.org/public/qj/proflevel/countryListing.cfm?promo=PWEBTOP&form_type=Professional)), the access to the full Safari library is included.

Or watch a lot of video courses if that's your preferred way of learning. Safari also has a lot of video content, but I'll also suggest a subscription to [Pluralsight](https://www.pluralsight.com/).

Another suggestion, you can learn a lot from other programming languages. For example, Java 9 is bringing modules to the language, but Javascript/Node.js has been dealing with modularity for a long time (AMD, CommonJS, etc.). The principles are the same, it's just learning another syntax (functional programming is another example of this).

**Comment by IvanMwiruki** [comment]
Thanks so much @eh3rrera !
