### ISSUE TITLE
Chapter 1 - Small typo and bad example for final keyword applied to classes

### ISSUE THREAD

**Issue by jlcscp** [eh3rrera/ocpj8-book#36]
There is a small typo in the Singleton section, before the first example on creating the instance in the get method. 
Where it says:

> However, **there will times** when for example, creating the object is not as simple as calling new, so the other way is to create the instance inside the get method

Sould be:

> However, there will **be** times when for example, (...)

The other issue I found is related to the use of the final keyword applied to a class.
Where it says:

> In turn, when final is applied to a class, you cannot subclass it. This is used when you don't want someone to change the behavior of a class by subclassing it. Two examples in the JDK are` java.lang.String` and **`java.lang.Number`**.

I think another class should be given as an example instead of **`java.lang.Number`**. In fact, this is an `abstract` class meant to be extended. A better example would be a subclass of `java.lang.Number`, such as` java.lang.Integer`, `java.lang.Long` or other.

**Comment by eh3rrera** [comment]
Thanks a lot, @jlcscp. You're right, I have made the suggested changes 👍
