### ISSUE TITLE
Minor Typo on Collections

### ISSUE THREAD

**Issue by GraveyGrumps** [eh3rrera/ocpj8-book#39]
**Original Example:**
Map<String, Integer> map = new TreeMap<>();

System.out.println( map.put("oranges", 7) ); // null
System.out.println( map.put("apples", 5) ); // null
System.out.println( map.put("lemons", 2) ); // null
System.out.println( map.put("bananas", 7) ); // null

// {apples=4 , bananas=7, lemons=2, oranges=7}
System.out.println(map);

// [apples, bananas, lemons, oranges]
Set<String> keys = map.keySet();
 Collection<Integer> values = map.values(); // [4, 7, 2, 7]

**Example Should Be:**
Map<String, Integer> map = new TreeMap<>();

System.out.println( map.put("oranges", 7) ); // null
System.out.println( map.put("apples", 5) ); // null
System.out.println( map.put("lemons", 2) ); // null
System.out.println( map.put("bananas", 7) ); // null

// {apples=5 , bananas=7, lemons=2, oranges=7}
System.out.println(map);

// [apples, bananas, lemons, oranges]
Set<String> keys = map.keySet();
 Collection<Integer> values = map.values(); // [5, 7, 2, 7]

**Comment by eh3rrera** [comment]
Thanks a lot @GraveyGrumps, it's fixed now.
