### ISSUE TITLE
Small mistake in Chapter 18 Parallel Streams

### ISSUE THREAD

**Issue by HermiGinger** [eh3rrera/ocpj8-book#4]
Mistake 
`stream.parallel().isParallel(); // false`

Correct
`stream.parallel().isParallel(); // true`

**Comment by eh3rrera** [comment]
Thanks again @HermiGinger 

It's fixed, can we close this issue?

**Comment by HermiGinger** [comment]
Thanks to you too sir!

This book is really a great source for OCP 1z0-809 aspirants. I find this better than some other materials I have used until now. It is easier to understand concepts from this book than others. Thanks a lot for publishing such an useful material.

**Comment by eh3rrera** [comment]
Thank you, that means a lot to me!

If you can, please help me spread the word about this book, thanks again.

**Comment by HermiGinger** [comment]
I will definitely do that sir!
