### ISSUE TITLE
In the chapter 27

### ISSUE THREAD

**Issue by avraamisvi** [eh3rrera/ocpj8-book#40]
You wrote the following:

> ConcurrentNavigableMap
> 
> It represents a thread-safe NavigableMap (like TreeSet) and is implemented by the ConcurrentSkipListMap class, sorted according to the natural ordering of its keys, or by a Comparator provided in its constructor.

But I think you meant TreeMap instead of TreeSet.

**Comment by eh3rrera** [comment]
You're right!

I have changed the text to reflect this, thanks a lot 👍
