### ISSUE TITLE
Deeper v/s shallower interface

### ISSUE THREAD

**Issue by dpanjabi** [eh3rrera/ocpj8-book#42]
Under "Interface inheritance with default methods" heading there is a line:
"More specific interfaces (or classes) always WIN over less specific ones. The default methods of the deeper interfaces in an inheritance hierarchy will be used."

Isn't should be:
"More specific interfaces (or classes) always WIN over less specific ones. The default methods of the **shallower** interfaces in an inheritance hierarchy will be used."

**Comment by eh3rrera** [comment]
Yes, you're right. It's fixed now, thanks a lot 👍

**Comment by dpanjabi** [comment]
Thanks a lot to you for such a nice tutorial. :)

**Comment by eh3rrera** [comment]
Thanks :)
