### ISSUE TITLE
No correct answers

### ISSUE THREAD

**Issue by aibeke** [eh3rrera/ocpj8-book#43]
Hello,
http://ocpj8.javastudyguide.com/ch23.html
Question 1 has no correct answer.
D. new PrintWriter(new OutputStream("file.txt"));

OutputStream is abstract class. You should to replace it with FileOutputStream.

Thank you for book.

**Comment by eh3rrera** [comment]
Hi,

Thanks for pointing out this error!

It should be fixed now 👍
