### ISSUE TITLE
Small mistake in Chapter 28 Fork/Join Framework

### ISSUE THREAD

**Issue by HermiGinger** [eh3rrera/ocpj8-book#5]
Mistake in key points section, last point

Mistake : You must first call **_join()_** (to queue the first subtask, then compute() (on the second subtask to process it recursively, and then join() to get the result of the first subtask).

Correct : You must first call **_fork()_** (to queue the first subtask, then compute() (on the second subtask to process it recursively, and then join() to get the result of the first subtask).

**Comment by eh3rrera** [comment]
Thanks again @HermiGinger! 

It's fixed. 👍
