### ISSUE TITLE
ch19: catch blocks : should use System.err

### ISSUE THREAD

**Issue by txpokey** [eh3rrera/ocpj8-book#54]
It's nit picking, but it's standard practice to use System.err to report exceptions.

E.g., when err is used on Intellij Idea, the color of the message is automatically changed to red, at least in the color scheme I use. Moreover, the application being built could run on the command line, where the shell can redirect stderr is it needs to. (That's true even on DOS and its successors.) 

So I think it's a useful change -- especially in Ch19 on exceptions and try-catch blocks, that you change to use 'err' and not 'out'. 

first example of this in ch19 is: 

> `catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("Exception caught");
        }`

it should read: 

> `catch(ArrayIndexOutOfBoundsException e) {
            System.err.println("Exception caught");
        }`

There are other occasions in Ch19 of this same problem, but I leave it up to you to ferret them out. 
HTH

**Comment by eh3rrera** [comment]
No problem, thanks for the pull request!
