### ISSUE TITLE
Clarification on multicatch

### ISSUE THREAD

**Issue by HermiGinger** [eh3rrera/ocpj8-book#6]
In the Questions section Question 3. It is asked to find out which all statements are true and from the options the statement

In a multi-catch block, if you declare more than one resource, they have to be separated by a **_semicolon_**.

is marked as true in answer section

isnt it supposed to be seperated by **_pipe operator_** instead of semi colon?

**Comment by eh3rrera** [comment]
Thanks again @HermiGinger,

The mistake is that the question isn't supposed to be about multi-catch blocks, but try-with-resources blocks (that's why the statement talks about resources and not about exceptions).

It's fixed now.

**Comment by eh3rrera** [comment]
Closed because there haven't been any activity for a long time.
