### ISSUE TITLE
ch22 : correcting type assignment and methodNameSpelling on ZonedDateTime examples

### ISSUE THREAD

**Issue by txpokey** [eh3rrera/ocpj8-book#60]
There's a set of related examples demonstrating that you can extract a LocalDate, LocalTime or a LocalDateTime from ZonedDateTime. But the assignments look like a copy-paste error, as they all assign to some variable of type LocalDateTime, instead of the respective types. LocalDate or LocalTime are not subtypes of LocalDateTime. 

After these, a couple lines later, there's a typo on use of:
         int day = now.getDayofMonth();
instead of:
         int day = now.getDayOfMonth();

**Comment by txpokey** [comment]
I closed the previous pull request, corrected my mistake on parens and then issued this new PR. apologies.

**Comment by eh3rrera** [comment]
Don't worry, it's merged now, thanks a lot! 👍
