### ISSUE TITLE
ch22: definition of newYear2001 is orphaned, needs clarification

### ISSUE THREAD

**Issue by txpokey** [eh3rrera/ocpj8-book#62]
so in ch22, there's this piece of code: 
```
        ZonedDateTime zdt8 = newYear2001.plus(2, ChronoUnit.HOURS);
```
except that the variable `newYear2001` is last defined in ch21 as a LocalDate, so the method `plus()` could run, but the assignment won't compile  to ZonedDateTime. 
since this zdt8 example is working on ZonedDateTime, I'd suggest making a change to something like the following:
```
        ZonedDateTime newYear2001 = LocalDate.of(2001, 1, 1).atStartOfDay(australiaZone);
        ZonedDateTime zdt8 = newYear2001.plus(2, ChronoUnit.HOURS);
```
or simplier yet, and following the approach of the previous zdt[0-7] examples:
```
        ZonedDateTime zdt8 = now.plus(2, ChronoUnit.HOURS);
```

**Comment by eh3rrera** [comment]
Yes, it should be:
```java
ZonedDateTime zdt8 = now.plus(2, ChronoUnit.HOURS);
```
Thanks!
