### ISSUE TITLE
Chapter 26 - Answers page

### ISSUE THREAD

**Issue by mabiosb** [eh3rrera/ocpj8-book#67]
I believe that the alternative of the letter 'A' is also correct.

> 1. Given:
> 
> ```
> ExecutorService service = Executors.newFixedThreadPool(2);
> Future result = service.submit(() -> 1);
> ```
> 
> Assuming it compiles correctly, what is the type of the lambda expression?
> **A. Runnable**
> **B. Callable**
> C. Supplier
> D. Function

**Comment by eh3rrera** [comment]
Well, while [submit](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#submit-java.lang.Runnable-) also takes a [Runnable](https://docs.oracle.com/javase/8/docs/api/java/lang/Runnable.html), the lambda expression in the question returns a value (`1`), so it has to be a [Callable](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Callable.html), which can return a value.

However, this question may be unnecessarily confusing, so I changed `Runnable` to `Predicate`.

Thanks!

**Comment by mabiosb** [comment]
Got it! Thanks for the explanation.
