### ISSUE TITLE
Answer key to Question5 From Interface chapter is wrong

### ISSUE THREAD

**Issue by protyay** [eh3rrera/ocpj8-book#70]
The answer key to the following question of Chapter 4(Q5) is *Compilation Fails.*
```
interface F {
    static void test() {
        System.out.println("F test");
    }
}
public class Question_4_5 implements F {
    public void test() {
        System.out.println("Q test");
    }
    public static void main(String[] args) {
        F q = new Question_4_5();
        q.test();
    }
}
```
I've executed the bit of this code and this compiles just fine and the output is "Q test".
Requesting you to please update the answer key accordingly.

**Comment by eh3rrera** [comment]
Are you sure? Are you testing with Java 8?

I don't know if I'm missing something but I get a compiler error:

![untitled-1](https://user-images.githubusercontent.com/11665759/46094745-545a9f80-c180-11e8-89c5-344e721668fe.png)

**Comment by protyay** [comment]
@eh3rrera I'm extremely sorry. I did happen to invoke the **test** routine on the reference type of the concrete class and *NOT* the interface.
Sorry for bothering you..

Keep up the great work.

**Comment by eh3rrera** [comment]
Don't worry, thanks! 👍
