### ISSUE TITLE
Enumeration question

### ISSUE THREAD

**Issue by zhengye1** [eh3rrera/ocpj8-book#72]
one of the explanation for the question is following:

> You can use the new operator inside an enum, but you cannot use the new operator to create a reference to an enum.

I get the second half of the statement, which means we cannot do this
```
enum Season{
   SPRING, SUMMER, AUTUMN, WINTER;
}

public class Test{
   public static void main(String[] args){
      Season s = new Season(); // Because constructor in Season is private
   }
}
```

But what is means 

> You can use the new operator inside an enum

and can you provide me an example for this?

**Comment by eh3rrera** [comment]
I was trying to create a tricky question, it doesn't have a special meaning.

I mean, an Enum can have fields, methods and constructors, and of course, you can use the new operator to instantiate the fields or other objects inside methods/constructors:
```java
public enum MyEnum {
    ONE(1), TWO(2);

    private BigDecimal asBigDecimal;
    private List<String> list = new ArrayList<String>();

    MyEnum(int i) {
        asBigDecimal = new BigDecimal(i);
    }
}
```

**Comment by zhengye1** [comment]
Thank you ~
