### ISSUE TITLE
Invalid answers in chapter 20

### ISSUE THREAD

**Issue by mamuf** [eh3rrera/ocpj8-book#73]
For the self-test question 3, the answers page correctly states what the command does, but this answer is not among the options of the test itself. None of the options matches the correct answer.

For the self-test question 5, the answers page states the incorrect answer. Just try to run the code from the question with `-ea`, it surely does not behave the same as the suggested answer. Unless the question should be a trick since it does not mention that assertions are enabled? I don't think that is the case.

**Comment by eh3rrera** [comment]
@mamuf The changes are published, thank you so much!

**Comment by mamuf** [comment]
@eh3rrera You are welcome, thanks for the fix!
