### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by doodsalc** [eh3rrera/ocpj8-book#75]
Minor typo in Chapter 24

In Example

Path path = Paths.get("c:\\temp\\dir1\file.txt");
for(Path name : path) {
    System.out.println(name);
}

It should instead have two slashes before file.txt like

Path path = Paths.get("c:\\temp\\dir1\\file.txt");

**Comment by eh3rrera** [comment]
Hi @doodsalc.

Thanks a lot, it's fixed.
