### ISSUE TITLE
Hi，I’m passed the exam.Here is some problems that I find

### ISSUE THREAD

**Issue by useager** [eh3rrera/ocpj8-book#98]
Hello !First I'm happy to path the exam by your project! Thank you very much!
If you don't nind I translated some chapter by computer and me on http://jtao.work/archives/guan-yu-zhe-pian-o-c-p---j-a-v-a-zhuan-ti-shuo-ming   
That is my blog,
And I also find some writing-error:

1.chapter 3

public class Question_3_1 {
     interface ITest { // 1
         void m();
     }
     public static void main(String args[]) {
         ITest t = new ITest() { // 2
             public void m() {
                 System.out.println("m()");
             }
         }      //should be };
         t.m();
     }
}

2.chapter 7

HashMap<String> m = new HashMap<>();  //should be HashMap<String,String> m=...  ??? t'm not sure
m.put(null, null);

3.chapter 12
int[] nums = {1, 2, 3, 4, 5};
When we create a stream from this array like this:
Stream.of(num)  //should be Stream.of(nums)

4.chapter 19
class MyResource implements AutoCloseable {
    public void close() throws Exception {
        int x = 0;
        //...
        if(x == 1) throw new Exception("Close Exception");
    }
    void useResource() {}
}
...
try (Resource r = new Resource()) { // Problem gone!    //here shoube MyResource r = new MyResource ()
    r.useResource();
} catch (Exception e) {
    e.printStackTrace();
}

5.chapter 22
ZoneID  //should be ZoneId
Represents the ID of time zone. For example, Asia/Tokyo.

6.chapter 23
try ( BufferedWriter bw =
     new BufferedWriter( new FileWriter("/file.txt") ) ) {
   w.write("Writing to the file...");  //should be   bw.write("Writing to the file...")
   w.newLine();  //should be bw.newLine()
} catch(IOException e) { /** ... */ }

7. chapter 29
try(Connection con =
      DriverManager.getConnection(url, user, passw);
      Statement stmt = con.createStatement()) {
   boolean hasResults = stmt.execute("SELECT * FROM user");
   if(hasResults) {
      // To retrieve the object with the results
      ResultSet rs = stmt.getResultSet()  //should be ResultSet rs = stmt.getResultSet();
   } else {
      // To get the number of affected rows
      int affectedRows = stmt.getUpdateCount();

I'm not good at english , best wishes for you!😀

**Comment by eh3rrera** [comment]
Hi, That's great, congratulations! Be sure to celebrate, this is hard exam 👍. 

Of course I don't mind, thank you so much for the translation.

Also thanks for spotting these errors, I've fixed them.

Best wishes for you too!
Esteban
